/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export type APIResource = {
    /**
     * The URL of the referenced resource.
     */
    url?: string | undefined;
    /**
     * The name of the referenced resource.
     */
    name?: string | undefined;
    /**
     * The ID of the referenced resource.
     */
    id?: number | undefined;
};

/** @internal */
export namespace APIResource$ {
    export type Inbound = {
        url?: string | undefined;
        name?: string | undefined;
        id?: number | undefined;
    };

    export const inboundSchema: z.ZodType<APIResource, z.ZodTypeDef, Inbound> = z
        .object({
            url: z.string().optional(),
            name: z.string().optional(),
            id: z.number().int().optional(),
        })
        .transform((v) => {
            return {
                ...(v.url === undefined ? null : { url: v.url }),
                ...(v.name === undefined ? null : { name: v.name }),
                ...(v.id === undefined ? null : { id: v.id }),
            };
        });

    export type Outbound = {
        url?: string | undefined;
        name?: string | undefined;
        id?: number | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, APIResource> = z
        .object({
            url: z.string().optional(),
            name: z.string().optional(),
            id: z.number().int().optional(),
        })
        .transform((v) => {
            return {
                ...(v.url === undefined ? null : { url: v.url }),
                ...(v.name === undefined ? null : { name: v.name }),
                ...(v.id === undefined ? null : { id: v.id }),
            };
        });
}
