/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export type BerryFirmness = {
    /**
     * The identifier for this berry firmness resource
     */
    id: number;
    /**
     * The name for this berry firmness resource
     */
    name: string;
};

/** @internal */
export namespace BerryFirmness$ {
    export type Inbound = {
        id: number;
        name: string;
    };

    export const inboundSchema: z.ZodType<BerryFirmness, z.ZodTypeDef, Inbound> = z
        .object({
            id: z.number().int(),
            name: z.string(),
        })
        .transform((v) => {
            return {
                id: v.id,
                name: v.name,
            };
        });

    export type Outbound = {
        id: number;
        name: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, BerryFirmness> = z
        .object({
            id: z.number().int(),
            name: z.string(),
        })
        .transform((v) => {
            return {
                id: v.id,
                name: v.name,
            };
        });
}
