/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { Language, Language$ } from "./language";
import { z } from "zod";

export type Description = {
    description?: string | undefined;
    language?: Language | undefined;
};

/** @internal */
export namespace Description$ {
    export type Inbound = {
        description?: string | undefined;
        language?: Language$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<Description, z.ZodTypeDef, Inbound> = z
        .object({
            description: z.string().optional(),
            language: Language$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                ...(v.description === undefined ? null : { description: v.description }),
                ...(v.language === undefined ? null : { language: v.language }),
            };
        });

    export type Outbound = {
        description?: string | undefined;
        language?: Language$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Description> = z
        .object({
            description: z.string().optional(),
            language: Language$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                ...(v.description === undefined ? null : { description: v.description }),
                ...(v.language === undefined ? null : { language: v.language }),
            };
        });
}
