/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export type EncounterMethod = {
    /**
     * The identifier for this encounter method resource
     */
    id: number;
    /**
     * The name for this encounter method resource
     */
    name: string;
    /**
     * A good value for sorting
     */
    order: number;
};

/** @internal */
export namespace EncounterMethod$ {
    export type Inbound = {
        id: number;
        name: string;
        order: number;
    };

    export const inboundSchema: z.ZodType<EncounterMethod, z.ZodTypeDef, Inbound> = z
        .object({
            id: z.number().int(),
            name: z.string(),
            order: z.number().int(),
        })
        .transform((v) => {
            return {
                id: v.id,
                name: v.name,
                order: v.order,
            };
        });

    export type Outbound = {
        id: number;
        name: string;
        order: number;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, EncounterMethod> = z
        .object({
            id: z.number().int(),
            name: z.string(),
            order: z.number().int(),
        })
        .transform((v) => {
            return {
                id: v.id,
                name: v.name,
                order: v.order,
            };
        });
}
