/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { Name, Name$ } from "./name";
import { NamedAPIResource, NamedAPIResource$ } from "./namedapiresource";
import { z } from "zod";

export type EncounterCondition = {
    /**
     * The identifier for this encounter condition resource
     */
    id: number;
    /**
     * The name for this encounter condition resource
     */
    name: string;
    /**
     * A list of values that are used with this encounter condition
     */
    values: Array<NamedAPIResource>;
    /**
     * The name of this encounter condition listed in different languages
     */
    names: Array<Name>;
};

/** @internal */
export namespace EncounterCondition$ {
    export type Inbound = {
        id: number;
        name: string;
        values: Array<NamedAPIResource$.Inbound>;
        names: Array<Name$.Inbound>;
    };

    export const inboundSchema: z.ZodType<EncounterCondition, z.ZodTypeDef, Inbound> = z
        .object({
            id: z.number().int(),
            name: z.string(),
            values: z.array(NamedAPIResource$.inboundSchema),
            names: z.array(Name$.inboundSchema),
        })
        .transform((v) => {
            return {
                id: v.id,
                name: v.name,
                values: v.values,
                names: v.names,
            };
        });

    export type Outbound = {
        id: number;
        name: string;
        values: Array<NamedAPIResource$.Outbound>;
        names: Array<Name$.Outbound>;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, EncounterCondition> = z
        .object({
            id: z.number().int(),
            name: z.string(),
            values: z.array(NamedAPIResource$.outboundSchema),
            names: z.array(Name$.outboundSchema),
        })
        .transform((v) => {
            return {
                id: v.id,
                name: v.name,
                values: v.values,
                names: v.names,
            };
        });
}
