/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { NamedAPIResource, NamedAPIResource$ } from "./namedapiresource";
import { z } from "zod";

export type FlavorText = {
    flavorText?: string | undefined;
    language?: NamedAPIResource | undefined;
    version?: NamedAPIResource | undefined;
};

/** @internal */
export namespace FlavorText$ {
    export type Inbound = {
        flavor_text?: string | undefined;
        language?: NamedAPIResource$.Inbound | undefined;
        version?: NamedAPIResource$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<FlavorText, z.ZodTypeDef, Inbound> = z
        .object({
            flavor_text: z.string().optional(),
            language: NamedAPIResource$.inboundSchema.optional(),
            version: NamedAPIResource$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                ...(v.flavor_text === undefined ? null : { flavorText: v.flavor_text }),
                ...(v.language === undefined ? null : { language: v.language }),
                ...(v.version === undefined ? null : { version: v.version }),
            };
        });

    export type Outbound = {
        flavor_text?: string | undefined;
        language?: NamedAPIResource$.Outbound | undefined;
        version?: NamedAPIResource$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, FlavorText> = z
        .object({
            flavorText: z.string().optional(),
            language: NamedAPIResource$.outboundSchema.optional(),
            version: NamedAPIResource$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                ...(v.flavorText === undefined ? null : { flavor_text: v.flavorText }),
                ...(v.language === undefined ? null : { language: v.language }),
                ...(v.version === undefined ? null : { version: v.version }),
            };
        });
}
