/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { NamedAPIResource, NamedAPIResource$ } from "./namedapiresource";
import { z } from "zod";

export type ItemCategory = {
    /**
     * The identifier for this item category resource
     */
    id?: number | undefined;
    /**
     * The name for this item category resource
     */
    name?: string | undefined;
    /**
     * A list of items that are a part of this category
     */
    items?: Array<NamedAPIResource> | undefined;
};

/** @internal */
export namespace ItemCategory$ {
    export type Inbound = {
        id?: number | undefined;
        name?: string | undefined;
        items?: Array<NamedAPIResource$.Inbound> | undefined;
    };

    export const inboundSchema: z.ZodType<ItemCategory, z.ZodTypeDef, Inbound> = z
        .object({
            id: z.number().int().optional(),
            name: z.string().optional(),
            items: z.array(NamedAPIResource$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ...(v.id === undefined ? null : { id: v.id }),
                ...(v.name === undefined ? null : { name: v.name }),
                ...(v.items === undefined ? null : { items: v.items }),
            };
        });

    export type Outbound = {
        id?: number | undefined;
        name?: string | undefined;
        items?: Array<NamedAPIResource$.Outbound> | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ItemCategory> = z
        .object({
            id: z.number().int().optional(),
            name: z.string().optional(),
            items: z.array(NamedAPIResource$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ...(v.id === undefined ? null : { id: v.id }),
                ...(v.name === undefined ? null : { name: v.name }),
                ...(v.items === undefined ? null : { items: v.items }),
            };
        });
}
