/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export type MoveBattleStyle = {
    id: number;
    name: string;
};

/** @internal */
export namespace MoveBattleStyle$ {
    export type Inbound = {
        id: number;
        name: string;
    };

    export const inboundSchema: z.ZodType<MoveBattleStyle, z.ZodTypeDef, Inbound> = z
        .object({
            id: z.number().int(),
            name: z.string(),
        })
        .transform((v) => {
            return {
                id: v.id,
                name: v.name,
            };
        });

    export type Outbound = {
        id: number;
        name: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, MoveBattleStyle> = z
        .object({
            id: z.number().int(),
            name: z.string(),
        })
        .transform((v) => {
            return {
                id: v.id,
                name: v.name,
            };
        });
}
