/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { NamedAPIResource, NamedAPIResource$ } from "./namedapiresource";
import { z } from "zod";

/**
 * Areas where the Pokémon species can be encountered in pal park.
 */
export type PalParkEncounterArea = {
    /**
     * The base score given to the player when the referenced Pokemon is caught during a pal park run.
     */
    baseScore?: number | undefined;
    /**
     * The base rate for encountering the referenced Pokemon in this pal park area.
     */
    rate?: number | undefined;
    area?: NamedAPIResource | undefined;
};

/** @internal */
export namespace PalParkEncounterArea$ {
    export type Inbound = {
        base_score?: number | undefined;
        rate?: number | undefined;
        area?: NamedAPIResource$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<PalParkEncounterArea, z.ZodTypeDef, Inbound> = z
        .object({
            base_score: z.number().int().optional(),
            rate: z.number().int().optional(),
            area: NamedAPIResource$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                ...(v.base_score === undefined ? null : { baseScore: v.base_score }),
                ...(v.rate === undefined ? null : { rate: v.rate }),
                ...(v.area === undefined ? null : { area: v.area }),
            };
        });

    export type Outbound = {
        base_score?: number | undefined;
        rate?: number | undefined;
        area?: NamedAPIResource$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PalParkEncounterArea> = z
        .object({
            baseScore: z.number().int().optional(),
            rate: z.number().int().optional(),
            area: NamedAPIResource$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                ...(v.baseScore === undefined ? null : { base_score: v.baseScore }),
                ...(v.rate === undefined ? null : { rate: v.rate }),
                ...(v.area === undefined ? null : { area: v.area }),
            };
        });
}
