/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { NamedAPIResource, NamedAPIResource$ } from "./namedapiresource";
import { z } from "zod";

export type PokemonStat = {
    stat?: NamedAPIResource | undefined;
    /**
     * The effort points (EV) the Pokémon has in the stat.
     */
    effort?: number | undefined;
    /**
     * The base value of the stat.
     */
    baseStat?: number | undefined;
};

/** @internal */
export namespace PokemonStat$ {
    export type Inbound = {
        stat?: NamedAPIResource$.Inbound | undefined;
        effort?: number | undefined;
        base_stat?: number | undefined;
    };

    export const inboundSchema: z.ZodType<PokemonStat, z.ZodTypeDef, Inbound> = z
        .object({
            stat: NamedAPIResource$.inboundSchema.optional(),
            effort: z.number().int().optional(),
            base_stat: z.number().int().optional(),
        })
        .transform((v) => {
            return {
                ...(v.stat === undefined ? null : { stat: v.stat }),
                ...(v.effort === undefined ? null : { effort: v.effort }),
                ...(v.base_stat === undefined ? null : { baseStat: v.base_stat }),
            };
        });

    export type Outbound = {
        stat?: NamedAPIResource$.Outbound | undefined;
        effort?: number | undefined;
        base_stat?: number | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PokemonStat> = z
        .object({
            stat: NamedAPIResource$.outboundSchema.optional(),
            effort: z.number().int().optional(),
            baseStat: z.number().int().optional(),
        })
        .transform((v) => {
            return {
                ...(v.stat === undefined ? null : { stat: v.stat }),
                ...(v.effort === undefined ? null : { effort: v.effort }),
                ...(v.baseStat === undefined ? null : { base_stat: v.baseStat }),
            };
        });
}
