/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { EncounterVersionDetails, EncounterVersionDetails$ } from "./encounterversiondetails";
import { NamedAPIResource, NamedAPIResource$ } from "./namedapiresource";
import { z } from "zod";

/**
 * Encounters Pokemon that can be encountered in the game and the version groups in which they can be encountered.
 */
export type PokemonEncounter = {
    pokemon?: NamedAPIResource | undefined;
    versionDetails?: Array<EncounterVersionDetails> | undefined;
};

/** @internal */
export namespace PokemonEncounter$ {
    export type Inbound = {
        pokemon?: NamedAPIResource$.Inbound | undefined;
        version_details?: Array<EncounterVersionDetails$.Inbound> | undefined;
    };

    export const inboundSchema: z.ZodType<PokemonEncounter, z.ZodTypeDef, Inbound> = z
        .object({
            pokemon: NamedAPIResource$.inboundSchema.optional(),
            version_details: z.array(EncounterVersionDetails$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ...(v.pokemon === undefined ? null : { pokemon: v.pokemon }),
                ...(v.version_details === undefined ? null : { versionDetails: v.version_details }),
            };
        });

    export type Outbound = {
        pokemon?: NamedAPIResource$.Outbound | undefined;
        version_details?: Array<EncounterVersionDetails$.Outbound> | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PokemonEncounter> = z
        .object({
            pokemon: NamedAPIResource$.outboundSchema.optional(),
            versionDetails: z.array(EncounterVersionDetails$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ...(v.pokemon === undefined ? null : { pokemon: v.pokemon }),
                ...(v.versionDetails === undefined ? null : { version_details: v.versionDetails }),
            };
        });
}
