/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export type PokemonColor = {
    /**
     * The identifier for this Pokemon color resource
     */
    id?: number | undefined;
    /**
     * The name for this Pokemon color resource
     */
    name?: string | undefined;
};

/** @internal */
export namespace PokemonColor$ {
    export type Inbound = {
        id?: number | undefined;
        name?: string | undefined;
    };

    export const inboundSchema: z.ZodType<PokemonColor, z.ZodTypeDef, Inbound> = z
        .object({
            id: z.number().int().optional(),
            name: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.id === undefined ? null : { id: v.id }),
                ...(v.name === undefined ? null : { name: v.name }),
            };
        });

    export type Outbound = {
        id?: number | undefined;
        name?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PokemonColor> = z
        .object({
            id: z.number().int().optional(),
            name: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.id === undefined ? null : { id: v.id }),
                ...(v.name === undefined ? null : { name: v.name }),
            };
        });
}
