/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { NamedAPIResource, NamedAPIResource$ } from "./namedapiresource";
import { z } from "zod";

export type PokemonEntry = {
    /**
     * The index number within the Pokédex.
     */
    entryNumber?: number | undefined;
    pokemonSpecies?: NamedAPIResource | undefined;
};

/** @internal */
export namespace PokemonEntry$ {
    export type Inbound = {
        entry_number?: number | undefined;
        pokemon_species?: NamedAPIResource$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<PokemonEntry, z.ZodTypeDef, Inbound> = z
        .object({
            entry_number: z.number().int().optional(),
            pokemon_species: NamedAPIResource$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                ...(v.entry_number === undefined ? null : { entryNumber: v.entry_number }),
                ...(v.pokemon_species === undefined ? null : { pokemonSpecies: v.pokemon_species }),
            };
        });

    export type Outbound = {
        entry_number?: number | undefined;
        pokemon_species?: NamedAPIResource$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PokemonEntry> = z
        .object({
            entryNumber: z.number().int().optional(),
            pokemonSpecies: NamedAPIResource$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                ...(v.entryNumber === undefined ? null : { entry_number: v.entryNumber }),
                ...(v.pokemonSpecies === undefined ? null : { pokemon_species: v.pokemonSpecies }),
            };
        });
}
