/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export type PokemonSprites = {
    /**
     * The default depiction of this Pokémon from the front in battle.
     */
    frontDefault?: string | undefined;
    /**
     * The shiny depiction of this Pokémon from the front in battle, for female gendered Pokémon.
     */
    frontFemale?: string | undefined;
    /**
     * The shiny depiction of this Pokémon from the front in battle.
     */
    frontShiny?: string | undefined;
    /**
     * The shiny depiction of this Pokémon from the front in battle, for female gendered Pokémon.
     */
    frontShinyFemale?: string | undefined;
    /**
     * The default depiction of this Pokémon from the back in battle.
     */
    backDefault?: string | undefined;
    /**
     * The shiny depiction of this Pokémon from the back in battle, for female gendered Pokémon.
     */
    backFemale?: string | undefined;
    /**
     * The shiny depiction of this Pokémon from the back in battle.
     */
    backShiny?: string | undefined;
    /**
     * The shiny depiction of this Pokémon from the back in battle, for female gendered Pokémon.
     */
    backShinyFemale?: string | undefined;
};

/** @internal */
export namespace PokemonSprites$ {
    export type Inbound = {
        front_default?: string | undefined;
        front_female?: string | undefined;
        front_shiny?: string | undefined;
        front_shiny_female?: string | undefined;
        back_default?: string | undefined;
        back_female?: string | undefined;
        back_shiny?: string | undefined;
        back_shiny_female?: string | undefined;
    };

    export const inboundSchema: z.ZodType<PokemonSprites, z.ZodTypeDef, Inbound> = z
        .object({
            front_default: z.string().optional(),
            front_female: z.string().optional(),
            front_shiny: z.string().optional(),
            front_shiny_female: z.string().optional(),
            back_default: z.string().optional(),
            back_female: z.string().optional(),
            back_shiny: z.string().optional(),
            back_shiny_female: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.front_default === undefined ? null : { frontDefault: v.front_default }),
                ...(v.front_female === undefined ? null : { frontFemale: v.front_female }),
                ...(v.front_shiny === undefined ? null : { frontShiny: v.front_shiny }),
                ...(v.front_shiny_female === undefined
                    ? null
                    : { frontShinyFemale: v.front_shiny_female }),
                ...(v.back_default === undefined ? null : { backDefault: v.back_default }),
                ...(v.back_female === undefined ? null : { backFemale: v.back_female }),
                ...(v.back_shiny === undefined ? null : { backShiny: v.back_shiny }),
                ...(v.back_shiny_female === undefined
                    ? null
                    : { backShinyFemale: v.back_shiny_female }),
            };
        });

    export type Outbound = {
        front_default?: string | undefined;
        front_female?: string | undefined;
        front_shiny?: string | undefined;
        front_shiny_female?: string | undefined;
        back_default?: string | undefined;
        back_female?: string | undefined;
        back_shiny?: string | undefined;
        back_shiny_female?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PokemonSprites> = z
        .object({
            frontDefault: z.string().optional(),
            frontFemale: z.string().optional(),
            frontShiny: z.string().optional(),
            frontShinyFemale: z.string().optional(),
            backDefault: z.string().optional(),
            backFemale: z.string().optional(),
            backShiny: z.string().optional(),
            backShinyFemale: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.frontDefault === undefined ? null : { front_default: v.frontDefault }),
                ...(v.frontFemale === undefined ? null : { front_female: v.frontFemale }),
                ...(v.frontShiny === undefined ? null : { front_shiny: v.frontShiny }),
                ...(v.frontShinyFemale === undefined
                    ? null
                    : { front_shiny_female: v.frontShinyFemale }),
                ...(v.backDefault === undefined ? null : { back_default: v.backDefault }),
                ...(v.backFemale === undefined ? null : { back_female: v.backFemale }),
                ...(v.backShiny === undefined ? null : { back_shiny: v.backShiny }),
                ...(v.backShinyFemale === undefined
                    ? null
                    : { back_shiny_female: v.backShinyFemale }),
            };
        });
}
