/**
 * poke-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AbilityGeneration } from '../models/AbilityGeneration';
import { AbilityNamesInner } from '../models/AbilityNamesInner';
import { HttpFile } from '../http/http';

export class Ability {
    /**
    * The identifier for this ability resource.
    */
    'id'?: number;
    /**
    * The name for this ability resource.
    */
    'name'?: string;
    /**
    * Whether or not this ability originated in the main series of the video games.
    */
    'isMainSeries'?: boolean;
    'generation'?: AbilityGeneration;
    'names'?: Array<AbilityNamesInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "isMainSeries",
            "baseName": "is_main_series",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "generation",
            "baseName": "generation",
            "type": "AbilityGeneration",
            "format": ""
        },
        {
            "name": "names",
            "baseName": "names",
            "type": "Array<AbilityNamesInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Ability.attributeTypeMap;
    }

    public constructor() {
    }
}

