/**
 * poke-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AbilityNamesInnerLanguage } from '../models/AbilityNamesInnerLanguage';
import { HttpFile } from '../http/http';

export class AbilityNamesInner {
    /**
    * The localized name for an API resource in a specific language.
    */
    'name'?: string;
    'language'?: AbilityNamesInnerLanguage;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "language",
            "baseName": "language",
            "type": "AbilityNamesInnerLanguage",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AbilityNamesInner.attributeTypeMap;
    }

    public constructor() {
    }
}

