/**
 * poke-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 20220523
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Ability } from "./Ability";
import { HttpFile } from "../http/http";

export class AbilityList200Response {
  /**
   * The total number of abilities available
   */
  "count"?: number;
  /**
   * The URL for the next page of abilities (null if none)
   */
  "next"?: string;
  /**
   * The URL for the previous page of abilities (null if none)
   */
  "previous"?: string;
  "results"?: Array<Ability>;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: "count",
      baseName: "count",
      type: "number",
      format: "",
    },
    {
      name: "next",
      baseName: "next",
      type: "string",
      format: "",
    },
    {
      name: "previous",
      baseName: "previous",
      type: "string",
      format: "",
    },
    {
      name: "results",
      baseName: "results",
      type: "Array<Ability>",
      format: "",
    },
  ];

  static getAttributeTypeMap() {
    return AbilityList200Response.attributeTypeMap;
  }

  public constructor() {}
}
