/**
 * poke-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FlavorText } from '../models/FlavorText';
import { VerboseEffect } from '../models/VerboseEffect';
import { HttpFile } from '../http/http';

export class ContestEffect {
    /**
    * The identifier for this contest effect resource
    */
    'id': number;
    /**
    * The base number of hearts the user of this move gets
    */
    'appeal': number;
    /**
    * The base number of hearts the user\'s opponent loses
    */
    'jam': number;
    /**
    * The flavor text of this contest effect listed in different languages
    */
    'effectEntries': Array<VerboseEffect>;
    /**
    * The flavor text of this contest effect listed in different languages
    */
    'flavorTextEntries': Array<FlavorText>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "appeal",
            "baseName": "appeal",
            "type": "number",
            "format": ""
        },
        {
            "name": "jam",
            "baseName": "jam",
            "type": "number",
            "format": ""
        },
        {
            "name": "effectEntries",
            "baseName": "effect_entries",
            "type": "Array<VerboseEffect>",
            "format": ""
        },
        {
            "name": "flavorTextEntries",
            "baseName": "flavor_text_entries",
            "type": "Array<FlavorText>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ContestEffect.attributeTypeMap;
    }

    public constructor() {
    }
}

