/**
 * poke-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EncounterConditionValue } from '../models/EncounterConditionValue';
import { EncounterMethod } from '../models/EncounterMethod';
import { HttpFile } from '../http/http';

export class Encounter {
    /**
    * The lowest level the Pokémon could be encountered at.
    */
    'minLevel': number;
    /**
    * The highest level the Pokémon could be encountered at.
    */
    'maxLevel': number;
    /**
    * The condition which triggers this encounter.
    */
    'conditionValues'?: Array<EncounterConditionValue>;
    /**
    * Percent chance that this encounter will occur.
    */
    'chance'?: number;
    'method': EncounterMethod;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "minLevel",
            "baseName": "min_level",
            "type": "number",
            "format": ""
        },
        {
            "name": "maxLevel",
            "baseName": "max_level",
            "type": "number",
            "format": ""
        },
        {
            "name": "conditionValues",
            "baseName": "condition_values",
            "type": "Array<EncounterConditionValue>",
            "format": ""
        },
        {
            "name": "chance",
            "baseName": "chance",
            "type": "number",
            "format": ""
        },
        {
            "name": "method",
            "baseName": "method",
            "type": "EncounterMethod",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Encounter.attributeTypeMap;
    }

    public constructor() {
    }
}

