/**
 * poke-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 20220523
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Description } from "./Description";
import { EggGroup } from "./EggGroup";
import { EvolutionChain } from "./EvolutionChain";
import { FlavorText } from "./FlavorText";
import { Generation } from "./Generation";
import { Genus } from "./Genus";
import { GrowthRate } from "./GrowthRate";
import { Name } from "./Name";
import { PalParkEncounterArea } from "./PalParkEncounterArea";
import { PokemonColor } from "./PokemonColor";
import { PokemonHabitat } from "./PokemonHabitat";
import { PokemonShape } from "./PokemonShape";
import { PokemonSpecies } from "./PokemonSpecies";
import { PokemonSpeciesDexEntry } from "./PokemonSpeciesDexEntry";
import { PokemonSpeciesVariety } from "./PokemonSpeciesVariety";
import { HttpFile } from "../http/http";

export class EvolutionChainChainEvolutionDetailsInnerPartySpecies {
  "id"?: number;
  "name"?: string;
  "order"?: number;
  "genderRate"?: number;
  "captureRate"?: number;
  "baseHappiness"?: number;
  "isBaby"?: boolean;
  "hatchCounter"?: number;
  "hasGenderDifferences"?: boolean;
  "formsSwitchable"?: boolean;
  "growthRate"?: GrowthRate;
  "pokedexNumbers"?: Array<PokemonSpeciesDexEntry>;
  "eggGroups"?: Array<EggGroup>;
  "color"?: PokemonColor;
  "shape"?: PokemonShape;
  "evolvesFromSpecies"?: PokemonSpecies;
  "evolutionChain"?: EvolutionChain;
  "habitat"?: PokemonHabitat;
  "generation"?: Generation;
  "names"?: Array<Name>;
  "palParkEncounters"?: Array<PalParkEncounterArea>;
  "flavorTextEntries"?: Array<FlavorText>;
  "formDescriptions"?: Array<Description>;
  "genera"?: Array<Genus>;
  "varieties"?: Array<PokemonSpeciesVariety>;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: "id",
      baseName: "id",
      type: "number",
      format: "int32",
    },
    {
      name: "name",
      baseName: "name",
      type: "string",
      format: "",
    },
    {
      name: "order",
      baseName: "order",
      type: "number",
      format: "int32",
    },
    {
      name: "genderRate",
      baseName: "gender_rate",
      type: "number",
      format: "int32",
    },
    {
      name: "captureRate",
      baseName: "capture_rate",
      type: "number",
      format: "int32",
    },
    {
      name: "baseHappiness",
      baseName: "base_happiness",
      type: "number",
      format: "int32",
    },
    {
      name: "isBaby",
      baseName: "is_baby",
      type: "boolean",
      format: "",
    },
    {
      name: "hatchCounter",
      baseName: "hatch_counter",
      type: "number",
      format: "int32",
    },
    {
      name: "hasGenderDifferences",
      baseName: "has_gender_differences",
      type: "boolean",
      format: "",
    },
    {
      name: "formsSwitchable",
      baseName: "forms_switchable",
      type: "boolean",
      format: "",
    },
    {
      name: "growthRate",
      baseName: "growth_rate",
      type: "GrowthRate",
      format: "",
    },
    {
      name: "pokedexNumbers",
      baseName: "pokedex_numbers",
      type: "Array<PokemonSpeciesDexEntry>",
      format: "",
    },
    {
      name: "eggGroups",
      baseName: "egg_groups",
      type: "Array<EggGroup>",
      format: "",
    },
    {
      name: "color",
      baseName: "color",
      type: "PokemonColor",
      format: "",
    },
    {
      name: "shape",
      baseName: "shape",
      type: "PokemonShape",
      format: "",
    },
    {
      name: "evolvesFromSpecies",
      baseName: "evolves_from_species",
      type: "PokemonSpecies",
      format: "",
    },
    {
      name: "evolutionChain",
      baseName: "evolution_chain",
      type: "EvolutionChain",
      format: "",
    },
    {
      name: "habitat",
      baseName: "habitat",
      type: "PokemonHabitat",
      format: "",
    },
    {
      name: "generation",
      baseName: "generation",
      type: "Generation",
      format: "",
    },
    {
      name: "names",
      baseName: "names",
      type: "Array<Name>",
      format: "",
    },
    {
      name: "palParkEncounters",
      baseName: "pal_park_encounters",
      type: "Array<PalParkEncounterArea>",
      format: "",
    },
    {
      name: "flavorTextEntries",
      baseName: "flavor_text_entries",
      type: "Array<FlavorText>",
      format: "",
    },
    {
      name: "formDescriptions",
      baseName: "form_descriptions",
      type: "Array<Description>",
      format: "",
    },
    {
      name: "genera",
      baseName: "genera",
      type: "Array<Genus>",
      format: "",
    },
    {
      name: "varieties",
      baseName: "varieties",
      type: "Array<PokemonSpeciesVariety>",
      format: "",
    },
  ];

  static getAttributeTypeMap() {
    return EvolutionChainChainEvolutionDetailsInnerPartySpecies.attributeTypeMap;
  }

  public constructor() {}
}
