/**
 * poke-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 20220523
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FlavorText } from "./FlavorText";
import { Item } from "./Item";
import { ItemAttribute } from "./ItemAttribute";
import { ItemCategory } from "./ItemCategory";
import { ItemFlingEffect } from "./ItemFlingEffect";
import { VerboseEffect } from "./VerboseEffect";
import { HttpFile } from "../http/http";

/**
 * The item that a baby Pokémon would be holding when born during a forced evolution
 */
export class EvolutionChainBabyTriggerItem {
  "id"?: number;
  "name"?: string;
  "cost"?: number;
  "flingPower"?: number;
  "effectEntries"?: Array<VerboseEffect>;
  "flavorTextEntries"?: Array<FlavorText>;
  "attributes"?: Array<ItemAttribute>;
  "category"?: ItemCategory;
  "flingEffect"?: ItemFlingEffect;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: "id",
      baseName: "id",
      type: "number",
      format: "int32",
    },
    {
      name: "name",
      baseName: "name",
      type: "string",
      format: "",
    },
    {
      name: "cost",
      baseName: "cost",
      type: "number",
      format: "int32",
    },
    {
      name: "flingPower",
      baseName: "fling_power",
      type: "number",
      format: "int32",
    },
    {
      name: "effectEntries",
      baseName: "effect_entries",
      type: "Array<VerboseEffect>",
      format: "",
    },
    {
      name: "flavorTextEntries",
      baseName: "flavor_text_entries",
      type: "Array<FlavorText>",
      format: "",
    },
    {
      name: "attributes",
      baseName: "attributes",
      type: "Array<ItemAttribute>",
      format: "",
    },
    {
      name: "category",
      baseName: "category",
      type: "ItemCategory",
      format: "",
    },
    {
      name: "flingEffect",
      baseName: "fling_effect",
      type: "ItemFlingEffect",
      format: "",
    },
  ];

  static getAttributeTypeMap() {
    return EvolutionChainBabyTriggerItem.attributeTypeMap;
  }

  public constructor() {}
}
