/**
 * poke-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 20220523
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EvolutionChainBabyTriggerItem } from "./EvolutionChainBabyTriggerItem";
import { EvolutionChainChain } from "./EvolutionChainChain";
import { HttpFile } from "../http/http";

export class EvolutionChain {
  /**
   * The identifier for this evolution chain resource
   */
  "id": number;
  "babyTriggerItem"?: EvolutionChainBabyTriggerItem | null;
  "chain": EvolutionChainChain;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: "id",
      baseName: "id",
      type: "number",
      format: "",
    },
    {
      name: "babyTriggerItem",
      baseName: "baby_trigger_item",
      type: "EvolutionChainBabyTriggerItem",
      format: "",
    },
    {
      name: "chain",
      baseName: "chain",
      type: "EvolutionChainChain",
      format: "",
    },
  ];

  static getAttributeTypeMap() {
    return EvolutionChain.attributeTypeMap;
  }

  public constructor() {}
}
