/**
 * poke-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { NamedAPIResource } from '../models/NamedAPIResource';
import { HttpFile } from '../http/http';

export class ItemCategory {
    /**
    * The identifier for this item category resource
    */
    'id'?: number;
    /**
    * The name for this item category resource
    */
    'name'?: string;
    /**
    * A list of items that are a part of this category
    */
    'items'?: Array<NamedAPIResource>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<NamedAPIResource>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ItemCategory.attributeTypeMap;
    }

    public constructor() {
    }
}

