/**
 * poke-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Name } from '../models/Name';
import { HttpFile } from '../http/http';

export class Language {
    'id'?: number;
    'name'?: string;
    'official'?: boolean;
    'iso639'?: string;
    'iso3166'?: string;
    'names'?: Array<Name>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "official",
            "baseName": "official",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "iso639",
            "baseName": "iso639",
            "type": "string",
            "format": ""
        },
        {
            "name": "iso3166",
            "baseName": "iso3166",
            "type": "string",
            "format": ""
        },
        {
            "name": "names",
            "baseName": "names",
            "type": "Array<Name>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Language.attributeTypeMap;
    }

    public constructor() {
    }
}

