/**
 * poke-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EncounterMethodRate } from '../models/EncounterMethodRate';
import { Location } from '../models/Location';
import { Name } from '../models/Name';
import { PokemonEncounter } from '../models/PokemonEncounter';
import { HttpFile } from '../http/http';

export class LocationArea {
    'id'?: number;
    'name'?: string;
    'gameIndex'?: number;
    'encounterMethodRates'?: Array<EncounterMethodRate>;
    'location'?: Location;
    'names'?: Array<Name>;
    'pokemonEncounters'?: Array<PokemonEncounter>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "gameIndex",
            "baseName": "game_index",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "encounterMethodRates",
            "baseName": "encounter_method_rates",
            "type": "Array<EncounterMethodRate>",
            "format": ""
        },
        {
            "name": "location",
            "baseName": "location",
            "type": "Location",
            "format": ""
        },
        {
            "name": "names",
            "baseName": "names",
            "type": "Array<Name>",
            "format": ""
        },
        {
            "name": "pokemonEncounters",
            "baseName": "pokemon_encounters",
            "type": "Array<PokemonEncounter>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LocationArea.attributeTypeMap;
    }

    public constructor() {
    }
}

