/**
 * poke-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 20220523
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { APIResource } from "./APIResource";
import { HttpFile } from "../http/http";

export class MachineVersionDetail {
  "machine": APIResource;
  "versionGroup": APIResource;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: "machine",
      baseName: "machine",
      type: "APIResource",
      format: "",
    },
    {
      name: "versionGroup",
      baseName: "version_group",
      type: "APIResource",
      format: "",
    },
  ];

  static getAttributeTypeMap() {
    return MachineVersionDetail.attributeTypeMap;
  }

  public constructor() {}
}
