/**
 * poke-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 20220523
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Description } from "./Description";
import { HttpFile } from "../http/http";

export class MoveDamageClass {
  "id": number;
  "name": string;
  "descriptions": Array<Description>;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: "id",
      baseName: "id",
      type: "number",
      format: "int32",
    },
    {
      name: "name",
      baseName: "name",
      type: "string",
      format: "",
    },
    {
      name: "descriptions",
      baseName: "descriptions",
      type: "Array<Description>",
      format: "",
    },
  ];

  static getAttributeTypeMap() {
    return MoveDamageClass.attributeTypeMap;
  }

  public constructor() {}
}
