/**
 * poke-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 20220523
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { NamedAPIResource } from "./NamedAPIResource";
import { HttpFile } from "../http/http";

export class MoveStatChange {
  /**
   * The amount of change to the referenced stat.
   */
  "change": number;
  "stat": NamedAPIResource;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: "change",
      baseName: "change",
      type: "number",
      format: "",
    },
    {
      name: "stat",
      baseName: "stat",
      type: "NamedAPIResource",
      format: "",
    },
  ];

  static getAttributeTypeMap() {
    return MoveStatChange.attributeTypeMap;
  }

  public constructor() {}
}
