/**
 * poke-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 20220523
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { NamedAPIResource } from "./NamedAPIResource";
import { HttpFile } from "../http/http";

export class Name {
  "language"?: NamedAPIResource;
  "name"?: string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: "language",
      baseName: "language",
      type: "NamedAPIResource",
      format: "",
    },
    {
      name: "name",
      baseName: "name",
      type: "string",
      format: "",
    },
  ];

  static getAttributeTypeMap() {
    return Name.attributeTypeMap;
  }

  public constructor() {}
}
