/**
 * poke-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 20220523
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Nature } from "./Nature";
import { HttpFile } from "../http/http";

export class NatureStatAffect {
  "increase"?: Array<Nature>;
  "decrease"?: Array<Nature>;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: "increase",
      baseName: "increase",
      type: "Array<Nature>",
      format: "",
    },
    {
      name: "decrease",
      baseName: "decrease",
      type: "Array<Nature>",
      format: "",
    },
  ];

  static getAttributeTypeMap() {
    return NatureStatAffect.attributeTypeMap;
  }

  public constructor() {}
}
