/**
 * poke-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 20220523
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PokeathlonStatName } from "./PokeathlonStatName";
import { HttpFile } from "../http/http";

export class NatureStatChange {
  "maxChange"?: number;
  "pokeathlonStat"?: PokeathlonStatName;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: "maxChange",
      baseName: "max_change",
      type: "number",
      format: "",
    },
    {
      name: "pokeathlonStat",
      baseName: "pokeathlon_stat",
      type: "PokeathlonStatName",
      format: "",
    },
  ];

  static getAttributeTypeMap() {
    return NatureStatChange.attributeTypeMap;
  }

  public constructor() {}
}
