/**
 * poke-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 20220523
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { NamedAPIResource } from "./NamedAPIResource";
import { VerboseEffect } from "./VerboseEffect";
import { HttpFile } from "../http/http";

export class PastMoveStatValuesEffectEntriesInner {
  "effect"?: VerboseEffect;
  "versionGroup"?: NamedAPIResource;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: "effect",
      baseName: "effect",
      type: "VerboseEffect",
      format: "",
    },
    {
      name: "versionGroup",
      baseName: "version_group",
      type: "NamedAPIResource",
      format: "",
    },
  ];

  static getAttributeTypeMap() {
    return PastMoveStatValuesEffectEntriesInner.attributeTypeMap;
  }

  public constructor() {}
}
