/**
 * poke-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PastMoveStatValuesEffectEntriesInner } from '../models/PastMoveStatValuesEffectEntriesInner';
import { Type } from '../models/Type';
import { HttpFile } from '../http/http';

export class PastMoveStatValues {
    /**
    * The percent value of how likely this move is to be successful.
    */
    'accuracy': number;
    /**
    * The percent value of effect occurring.
    */
    'effectChance'?: number;
    /**
    * The base power of this move with a value of 0 if it does not have a base power.
    */
    'power': number;
    /**
    * The power points this move has left.
    */
    'pp': number;
    /**
    * The list of previous effects this move has had across version groups.
    */
    'effectEntries'?: Array<PastMoveStatValuesEffectEntriesInner>;
    'type'?: Type;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "accuracy",
            "baseName": "accuracy",
            "type": "number",
            "format": ""
        },
        {
            "name": "effectChance",
            "baseName": "effect_chance",
            "type": "number",
            "format": ""
        },
        {
            "name": "power",
            "baseName": "power",
            "type": "number",
            "format": ""
        },
        {
            "name": "pp",
            "baseName": "pp",
            "type": "number",
            "format": ""
        },
        {
            "name": "effectEntries",
            "baseName": "effect_entries",
            "type": "Array<PastMoveStatValuesEffectEntriesInner>",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "Type",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PastMoveStatValues.attributeTypeMap;
    }

    public constructor() {
    }
}

