/**
 * poke-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 20220523
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Name } from "./Name";
import { HttpFile } from "../http/http";

export class PokeathlonStatName {
  "name"?: string;
  "names"?: Array<Name>;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: "name",
      baseName: "name",
      type: "string",
      format: "",
    },
    {
      name: "names",
      baseName: "names",
      type: "Array<Name>",
      format: "",
    },
  ];

  static getAttributeTypeMap() {
    return PokeathlonStatName.attributeTypeMap;
  }

  public constructor() {}
}
