/**
 * poke-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 20220523
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { NamedAPIResource } from "./NamedAPIResource";
import { HttpFile } from "../http/http";

export class PokemonMoveVersionGroupDetailsInner {
  /**
   * The minimum level to learn the move
   */
  "levelLearnedAt": number;
  "moveLearnMethod": NamedAPIResource;
  "versionGroup": NamedAPIResource;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: "levelLearnedAt",
      baseName: "level_learned_at",
      type: "number",
      format: "",
    },
    {
      name: "moveLearnMethod",
      baseName: "move_learn_method",
      type: "NamedAPIResource",
      format: "",
    },
    {
      name: "versionGroup",
      baseName: "version_group",
      type: "NamedAPIResource",
      format: "",
    },
  ];

  static getAttributeTypeMap() {
    return PokemonMoveVersionGroupDetailsInner.attributeTypeMap;
  }

  public constructor() {}
}
