/**
 * poke-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { NamedAPIResource } from '../models/NamedAPIResource';
import { PokemonMoveVersionGroupDetailsInner } from '../models/PokemonMoveVersionGroupDetailsInner';
import { HttpFile } from '../http/http';

export class PokemonMove {
    'move'?: NamedAPIResource;
    /**
    * A list of details showing how the Pokémon can learn the move 
    */
    'versionGroupDetails'?: Array<PokemonMoveVersionGroupDetailsInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "move",
            "baseName": "move",
            "type": "NamedAPIResource",
            "format": ""
        },
        {
            "name": "versionGroupDetails",
            "baseName": "version_group_details",
            "type": "Array<PokemonMoveVersionGroupDetailsInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PokemonMove.attributeTypeMap;
    }

    public constructor() {
    }
}

