/**
 * poke-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 20220523
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { NamedAPIResource } from "./NamedAPIResource";
import { PokemonAbility } from "./PokemonAbility";
import { PokemonForm } from "./PokemonForm";
import { PokemonHeldItem } from "./PokemonHeldItem";
import { PokemonMove } from "./PokemonMove";
import { PokemonSprites } from "./PokemonSprites";
import { PokemonStat } from "./PokemonStat";
import { PokemonType } from "./PokemonType";
import { VersionGameIndex } from "./VersionGameIndex";
import { HttpFile } from "../http/http";

export class Pokemon {
  "id": number;
  "name": string;
  "baseExperience": number;
  "height": number;
  "isDefault": boolean;
  "order": number;
  "weight": number;
  "abilities": Array<PokemonAbility>;
  "forms": Array<PokemonForm>;
  "gameIndices": Array<VersionGameIndex>;
  "heldItems": Array<PokemonHeldItem>;
  "locationAreaEncounters": string;
  "moves": Array<PokemonMove>;
  "sprites": PokemonSprites;
  "species": NamedAPIResource;
  "stats": Array<PokemonStat>;
  "types": Array<PokemonType>;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: "id",
      baseName: "id",
      type: "number",
      format: "int32",
    },
    {
      name: "name",
      baseName: "name",
      type: "string",
      format: "",
    },
    {
      name: "baseExperience",
      baseName: "base_experience",
      type: "number",
      format: "int32",
    },
    {
      name: "height",
      baseName: "height",
      type: "number",
      format: "int32",
    },
    {
      name: "isDefault",
      baseName: "is_default",
      type: "boolean",
      format: "",
    },
    {
      name: "order",
      baseName: "order",
      type: "number",
      format: "int32",
    },
    {
      name: "weight",
      baseName: "weight",
      type: "number",
      format: "int32",
    },
    {
      name: "abilities",
      baseName: "abilities",
      type: "Array<PokemonAbility>",
      format: "",
    },
    {
      name: "forms",
      baseName: "forms",
      type: "Array<PokemonForm>",
      format: "",
    },
    {
      name: "gameIndices",
      baseName: "game_indices",
      type: "Array<VersionGameIndex>",
      format: "",
    },
    {
      name: "heldItems",
      baseName: "held_items",
      type: "Array<PokemonHeldItem>",
      format: "",
    },
    {
      name: "locationAreaEncounters",
      baseName: "location_area_encounters",
      type: "string",
      format: "",
    },
    {
      name: "moves",
      baseName: "moves",
      type: "Array<PokemonMove>",
      format: "",
    },
    {
      name: "sprites",
      baseName: "sprites",
      type: "PokemonSprites",
      format: "",
    },
    {
      name: "species",
      baseName: "species",
      type: "NamedAPIResource",
      format: "",
    },
    {
      name: "stats",
      baseName: "stats",
      type: "Array<PokemonStat>",
      format: "",
    },
    {
      name: "types",
      baseName: "types",
      type: "Array<PokemonType>",
      format: "",
    },
  ];

  static getAttributeTypeMap() {
    return Pokemon.attributeTypeMap;
  }

  public constructor() {}
}
