/**
 * poke-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 20220523
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { NaturePokeathlonStatAffectSets } from "./NaturePokeathlonStatAffectSets";
import { HttpFile } from "../http/http";

/**
 * A detail of natures which affect this Pokéathlon stat positively or negatively
 */
export class PokeathlonStatAffectingNatures {
  /**
   * A list of natures that positively affect this Pokéathlon stat
   */
  "increase"?: Array<NaturePokeathlonStatAffectSets>;
  /**
   * A list of natures that negatively affect this Pokéathlon stat
   */
  "decrease"?: Array<NaturePokeathlonStatAffectSets>;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: "increase",
      baseName: "increase",
      type: "Array<NaturePokeathlonStatAffectSets>",
      format: "",
    },
    {
      name: "decrease",
      baseName: "decrease",
      type: "Array<NaturePokeathlonStatAffectSets>",
      format: "",
    },
  ];

  static getAttributeTypeMap() {
    return PokeathlonStatAffectingNatures.attributeTypeMap;
  }

  public constructor() {}
}
