/**
 * poke-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 20220523
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Description } from "./Description";
import { NamedAPIResource } from "./NamedAPIResource";
import { PokemonEntry } from "./PokemonEntry";
import { HttpFile } from "../http/http";

export class Pokedex {
  "id": number;
  "name": string;
  "isMainSeries": boolean;
  "descriptions": Array<Description>;
  "pokemonEntries": Array<PokemonEntry>;
  "region": NamedAPIResource;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: "id",
      baseName: "id",
      type: "number",
      format: "",
    },
    {
      name: "name",
      baseName: "name",
      type: "string",
      format: "",
    },
    {
      name: "isMainSeries",
      baseName: "is_main_series",
      type: "boolean",
      format: "",
    },
    {
      name: "descriptions",
      baseName: "descriptions",
      type: "Array<Description>",
      format: "",
    },
    {
      name: "pokemonEntries",
      baseName: "pokemon_entries",
      type: "Array<PokemonEntry>",
      format: "",
    },
    {
      name: "region",
      baseName: "region",
      type: "NamedAPIResource",
      format: "",
    },
  ];

  static getAttributeTypeMap() {
    return Pokedex.attributeTypeMap;
  }

  public constructor() {}
}
