/**
 * poke-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TypeGameIndicesInnerGeneration } from '../models/TypeGameIndicesInnerGeneration';
import { HttpFile } from '../http/http';

export class TypeGameIndicesInner {
    /**
    * The internal id of an api resource within game data.
    */
    'gameIndex'?: number;
    'generation'?: TypeGameIndicesInnerGeneration;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "gameIndex",
            "baseName": "game_index",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "generation",
            "baseName": "generation",
            "type": "TypeGameIndicesInnerGeneration",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TypeGameIndicesInner.attributeTypeMap;
    }

    public constructor() {
    }
}

